=== Leonardo-Chiarparin/Tesina-LWEB-2023-24/XML/Schema/Discussioni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="discussioni">
		<xsd:complexType> 
			<xsd:sequence>
				<xsd:element ref="discussione" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="ultimoId" type="xsd:integer" use="required" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="discussione">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="titolo" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="descrizione" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="interventi" minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:positiveInteger" use="required" />
			<xsd:attribute name="idAutore" type="xsd:positiveInteger" use="required" />
			<xsd:attribute name="dataOraIssue" type="xsd:string" use="required" />
			<xsd:attribute name="moderata" use="required">
				<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="No"/>
							<xsd:enumeration value="Si"/>
						</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="risolta" use="required">
				<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="No"/>
							<xsd:enumeration value="Si"/>
						</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="titolo" type="xsd:string" />
	<xsd:element name="descrizione" type="xsd:string" />
	
	<xsd:element name="interventi">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="intervento" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="ultimoId" type="xsd:integer" use="required" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="intervento">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="testo" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="valutazioni" minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:positiveInteger" use="required" />
			<xsd:attribute name="idPartecipante" type="xsd:positiveInteger" use="required" />
			<xsd:attribute name="dataOraIssue" type="xsd:string" use="required" />
			<xsd:attribute name="moderato" use="required">
				<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="No"/>
							<xsd:enumeration value="Si"/>
						</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="testo" type="xsd:string" />

	<xsd:element name="valutazioni">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="valutazione" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="valutazione">
		<xsd:complexType>
			<xsd:attribute name="idVotante" type="xsd:positiveInteger" use="required" />
			<xsd:attribute name="supporto" use="required">
				<xsd:simpleType>
						<xsd:restriction base="xsd:positiveInteger">
							<xsd:minInclusive value="1"/>
							<xsd:maxInclusive value="5"/>
						</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="utilita" use="required">
				<xsd:simpleType>
						<xsd:restriction base="xsd:positiveInteger">
							<xsd:minInclusive value="1"/>
							<xsd:maxInclusive value="5"/>
						</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== Leonardo-Chiarparin/Tesina-LWEB-2023-24/XML/Discussioni.xml
<?xml version="1.0" encoding="UTF-8"?>

<discussioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema/Discussioni.xsd" ultimoId="1">
	<discussione id="1" idAutore="6" dataOraIssue="2024-06-03 10:32:00" moderata="No" risolta="Si">
		<titolo>Offline?</titolo>
		<descrizione>È richiesto l'abbonamento a PlayStation Plus oppure si può giocare anche senza?</descrizione>
		<interventi ultimoId="2">
			<intervento id="1" idPartecipante="4" dataOraIssue="2024-06-03 14:17:00" moderato="No">
				<testo>
				  Puoi giocare anche offline. Però ti assicuro che la modalità online ti può aiutare molto nei momenti in cui il gioco si fa estremamente difficile. Puoi chiedere il supporto di un altro giocatore scrivendo un messaggio nella community di Bloodborne su PS, così facendo il suo cacciatore interverrà direttamente nel tuo scenario di gioco e ti sosterrà contro i Boss più ostici.
				</testo>
				<valutazioni>
					<valutazione idVotante="6" supporto="5" utilita="5"></valutazione>
				</valutazioni>
			</intervento>
			<intervento id="2" idPartecipante="5" dataOraIssue="2024-06-03 15:00:00" moderato="Si">
				<testo>
				  Domanda inutile a mio avviso... Ti basta fare una ricerca su Internet!!!
				</testo>
				<valutazioni>
				</valutazioni>
			</intervento>
		</interventi>
	</discussione>
</discussioni>
