=== Leonardo-Chiarparin/Tesina-LWEB-2023-24/XML/Schema/FAQ.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="faq">
		<xsd:complexType> 
			<xsd:sequence>
				<xsd:element ref="singolaFaq" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="ultimoId" type="xsd:integer" use="required" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="singolaFaq">
		<xsd:complexType> 
			<xsd:sequence>
				<xsd:element ref="resocontoDiscussione" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="interventoDiscussione" minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:positiveInteger" use="required" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="resocontoDiscussione">
		<xsd:complexType>
			<xsd:choice>
				<xsd:element ref="discussioneDaZero" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="discussioneEsistente" minOccurs="1" maxOccurs="1" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>	
	
	<xsd:element name="discussioneDaZero">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="titolo" type="xsd:string" minOccurs="1" maxOccurs="1" />
				<xsd:element name="descrizione" type="xsd:string" minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>	
	
	<xsd:element name="discussioneEsistente">
		<xsd:complexType>
			<xsd:attribute name="idDiscussione" type="xsd:positiveInteger" use="required" />
		</xsd:complexType>
	</xsd:element>	
	
	<xsd:element name="interventoDiscussione">
		<xsd:complexType>
			<xsd:choice>
				<xsd:element ref="interventoDaZero" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="interventoEsistente" minOccurs="1" maxOccurs="1" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>	
	
	<xsd:element name="interventoDaZero">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="testo" type="xsd:string" minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>	
	
	<xsd:element name="interventoEsistente">
		<xsd:complexType>
			<xsd:attribute name="idIntervento" type="xsd:positiveInteger" use="required" />
		</xsd:complexType>
	</xsd:element>	
	
</xsd:schema>

=== Leonardo-Chiarparin/Tesina-LWEB-2023-24/XML/FAQ.xml
<?xml version="1.0" encoding="UTF-8"?>
<faq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema/FAQ.xsd" ultimoId="1">
	<singolaFaq id="1">
		<resocontoDiscussione>
			<discussioneDaZero>
				<titolo>Indirizzo di consegna diverso</titolo>
				<descrizione>Come posso cambiare l'indirizzo di spedizione prima di procedere con il pagamento dell'ordine?</descrizione>
			</discussioneDaZero>
		</resocontoDiscussione>
		<interventoDiscussione>
			<interventoDaZero>
				<testo>
					Se hai bisogno di modificare l'ubicazione a cui recapitare gli articoli da acquistare, è possibile compilare il relativo modulo nella schermata di conferma dell'acquisto. Proprio per questo, non avere timore di apportare dei cambiamenti alle tue 
					preferenze.
				</testo>
			</interventoDaZero>
		</interventoDiscussione>
	</singolaFaq>
</faq>
