=== Leonardo-Chiarparin/Tesina-LWEB-2023-24/XML/Schema/Offerte.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="offerte">
		<xsd:complexType> 
			<xsd:sequence>
				<xsd:element ref="offerta" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="ultimoId" type="xsd:integer" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="offerta">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="prezzoContabile" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="sconto" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="quantitativo" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="bonus" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
	   
			<xsd:attribute name="id" type="xsd:positiveInteger" use="required" />
			<xsd:attribute name="idProdotto" type="xsd:positiveInteger" use="required" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="prezzoContabile" type="xsd:decimal"/>
	<xsd:element name="quantitativo" type="xsd:integer"/>
	<xsd:element name="sconto" type="riduzione"/>
	<xsd:element name="bonus" type="incentivo" />
	
	<xsd:complexType name="riduzione">
		<xsd:choice>
			<xsd:element ref="scontoATempo" minOccurs="1" maxOccurs="1" />
			<xsd:element ref="scontoFuturo" minOccurs="1" maxOccurs="1" />
		</xsd:choice>
	</xsd:complexType>
	
	<xsd:element name="scontoATempo">
		<xsd:complexType>	
			<xsd:attribute name="percentuale" type="xsd:decimal" use="required" />
			<xsd:attribute name="inizioApplicazione" type="xsd:date" use="required" />
			<xsd:attribute name="fineApplicazione" type="xsd:date" use="required" />
		</xsd:complexType>
	</xsd:element>
		
	<xsd:element name="scontoFuturo">	
		<xsd:complexType>	
			<xsd:attribute name="percentuale" type="xsd:decimal" use="required" />
			<xsd:attribute name="inizioApplicazione" type="xsd:date" use="required" />
			<xsd:attribute name="fineApplicazione" type="xsd:date" use="required" />
		</xsd:complexType>
	</xsd:element>
		
	<xsd:complexType name="incentivo">
		<xsd:sequence>
			<xsd:element ref="numeroCrediti" minOccurs="1" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
			
	<xsd:element name="numeroCrediti" type="xsd:decimal" />
	
</xsd:schema>

=== Leonardo-Chiarparin/Tesina-LWEB-2023-24/XML/Offerte.xml
<?xml version="1.0" encoding="UTF-8"?>

<offerte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema/Offerte.xsd" ultimoId="2">
	<offerta id="1" idProdotto="1">
		<prezzoContabile>52.45</prezzoContabile>
		<quantitativo>29</quantitativo>
		<bonus>
			<numeroCrediti>25.00</numeroCrediti>
		</bonus>
	</offerta>
	<offerta id="2" idProdotto="2">
		<prezzoContabile>84.50</prezzoContabile>
		<sconto>
			<scontoFuturo percentuale="2.00" inizioApplicazione="2024-06-01" fineApplicazione="2024-09-01"></scontoFuturo>
		</sconto>
		<quantitativo>29</quantitativo>
	</offerta>
</offerte>
