=== Leonardo-Chiarparin/Tesina-LWEB-2023-24/XML/Dtd/Prodotti.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT prodotti (prodotto*)>

<!ELEMENT prodotto (nome, tipologia, descrizione, immagine, prezzoListino, annoUscita, recensioni, discussioni)>
<!ATTLIST prodotto 
			id CDATA #REQUIRED>
			
<!ELEMENT nome (#PCDATA)>

<!ELEMENT tipologia (libro|videogioco)>

<!ELEMENT libro (categorie, autori)>

<!ELEMENT categorie (categoria+)>
<!ELEMENT categoria EMPTY>
<!ATTLIST categoria
			idCategoria CDATA #REQUIRED>

<!ELEMENT autori (autore+)>
<!ELEMENT autore (nome, cognome?)>
<!ELEMENT cognome (#PCDATA)>

<!ELEMENT videogioco (piattaforma, generi, casaProduzione)>

<!ELEMENT piattaforma EMPTY>
<!ATTLIST piattaforma
			idPiattaforma CDATA #REQUIRED>

<!ELEMENT generi (genere+)>
<!ELEMENT genere EMPTY>
<!ATTLIST genere
			idGenere CDATA #REQUIRED>
			
<!ELEMENT casaProduzione (#PCDATA)>	

<!ELEMENT descrizione (#PCDATA)>	

<!ELEMENT immagine (#PCDATA)>	

<!ELEMENT prezzoListino (#PCDATA)>	

<!ELEMENT annoUscita (#PCDATA)>	

<!ELEMENT recensioni (recensione*)>
<!ELEMENT recensione EMPTY>
<!ATTLIST recensione 
			idRecensione CDATA #REQUIRED>

<!ELEMENT discussioni (discussione*)>
<!ELEMENT discussione EMPTY>
<!ATTLIST discussione 
			idDiscussione CDATA #REQUIRED>

=== Leonardo-Chiarparin/Tesina-LWEB-2023-24/XML/Prodotti.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE prodotti SYSTEM "Dtd/Prodotti.dtd">

<prodotti>
	<prodotto id="1">
		<nome>Bloodborne</nome>
		<tipologia>
			<videogioco>
				<piattaforma idPiattaforma="1"></piattaforma>
				<generi>
					<genere idGenere="1"></genere>
					<genere idGenere="2"></genere>
				</generi>
				<casaProduzione>FromSoftware</casaProduzione>
			</videogioco>
		</tipologia>
		<descrizione>Un incredibile viaggio in una città gotica ricostruita con una dovizia di dettagli e popolata da incubi e tenebre!</descrizione>
		<immagine>../Immagini/Bloodborne_Ps4.jpg</immagine>
		<prezzoListino>104.95</prezzoListino>
		<annoUscita>2015</annoUscita>
		<recensioni>
			<recensione idRecensione="1"></recensione>
		</recensioni>
		<discussioni>
			<discussione idDiscussione="1"></discussione>
		</discussioni>
	</prodotto>
	<prodotto id="2">
		<nome>Fuga dal campo 14</nome>
		<tipologia>
			<libro>
				<categorie>
					<categoria idCategoria="1"></categoria>
				</categorie>
				<autori>
					<autore>
						<nome>Blain</nome>
						<cognome>Harden</cognome>
					</autore>
				</autori>
			</libro>
		</tipologia>
		<descrizione>Shin Dong-hyuk è l'unico uomo nato in un campo di prigionia della Corea del Nord ad essere riuscito a scappare. La sua fuga e il libro che la racconta sono diventati un caso internazionale, che ha convinto le Nazioni Unite a costituire una commissione d'indagine sui campi di prigionia nordcoreani. Il Campo 14 è grande quanto Los Angeles, ed è visibile su Google Maps: eppure resta invisibile agli occhi del mondo. Il crimine che Shin ha commesso è avere uno zio che negli anni cinquanta fuggì in Corea del Sud; nasce quindi nel 1982 dietro il filo spinato del campo, dove la sua famiglia è stata rinchiusa da decenni. Non sa che esiste il mondo esterno, ed è a tutti gli effetti uno schiavo. Solo a ventitré anni riuscirà a fuggire, grazie all'aiuto di un compagno che tenterà la fuga con lui, e ad arrivare a piedi e con vestiti di fortuna in Cina, e da lì in America. Questa è la sua storia.</descrizione>
		<immagine>../Immagini/Fuga_dal_Campo_14.jpg</immagine>
		<prezzoListino>84.50</prezzoListino>
		<annoUscita>2012</annoUscita>
		<recensioni>
			<recensione idRecensione="2"></recensione>
		</recensioni>
		<discussioni>
		</discussioni>
	</prodotto>
</prodotti>
