=== Leonardo-Chiarparin/Tesina-LWEB-2023-24/XML/Dtd/Recensioni_Prodotti.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT recensioni (recensione*)>
<!ATTLIST recensioni 
			ultimoId CDATA #REQUIRED>
			
<!ELEMENT recensione (titolo, testo, valutazione)>
<!ATTLIST recensione
			id CDATA #REQUIRED
			idCliente CDATA #REQUIRED
			dataPubblicazione CDATA #REQUIRED>

<!ELEMENT titolo (#PCDATA)>

<!ELEMENT testo (#PCDATA)>

<!ELEMENT valutazione (perLibro|perVideogioco)>

<!ELEMENT perLibro EMPTY>
<!ATTLIST perLibro 		
			trama CDATA #REQUIRED
			caratterizzazionePersonaggi CDATA #REQUIRED
			ambientazione CDATA #REQUIRED>
			
<!ELEMENT perVideogioco EMPTY>
<!ATTLIST perVideogioco 
			sceneggiatura CDATA #REQUIRED
			tecnica CDATA #REQUIRED
			giocabilita CDATA #REQUIRED>

=== Leonardo-Chiarparin/Tesina-LWEB-2023-24/XML/Recensioni_Prodotti.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recensioni SYSTEM "Dtd/Recensioni_Prodotti.dtd">

<recensioni ultimoId="2">
	<recensione id="1" idCliente="4" dataPubblicazione="2024-06-01">
		<titolo>Bloodborne PS4</titolo>
		<testo>Bloodborne è un'esperienza di gioco impeccabile. L'ambientazione gotica e il gameplay frenetico creano una tensione costante. La sfida elevata rende ogni vittoria gratificante. Il design dei nemici e dei livelli è stupefacente. Un capolavoro assoluto.</testo>
		<valutazione>
			<perVideogioco sceneggiatura="5" tecnica="5" giocabilita="5"></perVideogioco>
		</valutazione>
	</recensione>
	<recensione id="2" idCliente="6" dataPubblicazione="2024-06-07">
		<titolo>Per non voltarsi dall'altra parte</titolo>
		<testo>Non è la prima volta che leggo della Corea del Nord eppure questo libro è riuscito davvero a stupirmi. Mostra uno spaccato di quell'orribile realtà quotidiana che sono i campi di lavoro nordcoreani. Mostra qualcosa di simile e contemporaneamente diverso e peggiore rispetto ai gulag e ai campi di concentramento; qualcosa che da 50 anni ad oggi non ha fine! Oltre alla tragica esperienza di Shin però questo libro è anche un utile strumento per chiunque voglia farsi un'idea di quello che è la Corea del Nord, la sua società, la sua economia e la sua politica. Ci tengo anche a fare presente che Harden ha dotato ogni capitolo di un buon apparato di note che può indurre chi è interessato ad ulteriori approfondimenti (quasi tutte le fonti sono in inglese e molte sono reperibili gratuitamente in rete tramite le organizzazioni che si occupano della Corea del Nord).</testo>
		<valutazione>
			<perLibro trama="5" caratterizzazionePersonaggi="4" ambientazione="5"></perLibro>
		</valutazione>
	</recensione>
</recensioni>
