=== Leonardo-Chiarparin/Tesina-LWEB-2023-24/XML/Dtd/Riduzioni_Prezzi.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT riduzioni (riduzione*)>

<!ELEMENT riduzione (sconti)>
<!ATTLIST riduzione
			idCliente CDATA #REQUIRED>

<!ELEMENT sconti (aSoglia, fedeltaElite, acquistoPromozionale, perVIP, diAnzianita)>
<!ELEMENT aSoglia EMPTY>
<!ATTLIST aSoglia
			idTariffaSoglia CDATA #REQUIRED
			creditiSpesi CDATA #REQUIRED
			superamenti CDATA #REQUIRED
			fruibile CDATA #REQUIRED>

<!ELEMENT fedeltaElite EMPTY>
<!ATTLIST fedeltaElite 
			idTariffaFedeltaElite CDATA #REQUIRED
			creditiSpesi CDATA #REQUIRED
			superamenti CDATA #REQUIRED
			fruibile CDATA #REQUIRED
			esercitabile CDATA #REQUIRED>
			
<!ELEMENT acquistoPromozionale (percentuale)>

<!ELEMENT percentuale (#PCDATA)>
		
<!ELEMENT perVIP EMPTY>
<!ATTLIST perVIP 
			idTariffaPerVIP CDATA #REQUIRED
			fruibile CDATA #REQUIRED>

<!ELEMENT diAnzianita (percentuale)>
<!ATTLIST diAnzianita 
			idTariffaDiAnzianita CDATA #REQUIRED
			fruibile CDATA #REQUIRED>

=== Leonardo-Chiarparin/Tesina-LWEB-2023-24/XML/Riduzioni_Prezzi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE riduzioni SYSTEM "Dtd/Riduzioni_Prezzi.dtd">

<riduzioni>
	<riduzione idCliente="4">
		<sconti>
			<aSoglia idTariffaSoglia="1" creditiSpesi="52.45" superamenti="0" fruibile="0"></aSoglia>
			<fedeltaElite idTariffaFedeltaElite="2" creditiSpesi="52.45" superamenti="0" fruibile="0" esercitabile="1"></fedeltaElite>
			<acquistoPromozionale>
				<percentuale>0.00</percentuale>
			</acquistoPromozionale>
			<perVIP idTariffaPerVIP="3" fruibile="0"></perVIP>
			<diAnzianita idTariffaDiAnzianita="4" fruibile="0">
				<percentuale>0.00</percentuale>
			</diAnzianita>
		</sconti>
	</riduzione>
	<riduzione idCliente="5">
		<sconti>
			<aSoglia idTariffaSoglia="1" creditiSpesi="0.00" superamenti="0" fruibile="0"></aSoglia>
			<fedeltaElite idTariffaFedeltaElite="2" creditiSpesi="0.00" superamenti="0" fruibile="0" esercitabile="1"></fedeltaElite>
			<acquistoPromozionale>
				<percentuale>0.00</percentuale>
			</acquistoPromozionale>
			<perVIP idTariffaPerVIP="3" fruibile="0"></perVIP>
			<diAnzianita idTariffaDiAnzianita="4" fruibile="0">
				<percentuale>0.00</percentuale>
			</diAnzianita>
		</sconti>
	</riduzione>
	<riduzione idCliente="6">
		<sconti>
			<aSoglia idTariffaSoglia="1" creditiSpesi="0.00" superamenti="0" fruibile="0"></aSoglia>
			<fedeltaElite idTariffaFedeltaElite="2" creditiSpesi="0.00" superamenti="0" fruibile="0" esercitabile="1"></fedeltaElite>
			<acquistoPromozionale>
				<percentuale>0.00</percentuale>
			</acquistoPromozionale>
			<perVIP idTariffaPerVIP="3" fruibile="0"></perVIP>
			<diAnzianita idTariffaDiAnzianita="4" fruibile="0">
				<percentuale>0.00</percentuale>
			</diAnzianita>
		</sconti>
	</riduzione>
</riduzioni>
